-- ##### POPULANDO A TABELA COM DADOS FICTÍCIOS ##### --

-- ##STATUS
INSERT INTO status (name, description) VALUES
('Aberto', 'Ticket criado e aguardando atendimento'),
('Em andamento', 'Ticket sendo tratado pelo agente'),
('Pendente', 'Aguardando resposta do cliente ou de terceiros'),
('Resolvido','Solução aplicada e aguardando confirmação do cliente'),
('Fechado', 'Ticket encerrado com sucesso');


-- ##CATEGORIES
INSERT INTO categories(name, description) VALUES
('Suporte Técnico', 'Problemas relacionados a software, hardware ou sistemas'),
('Financeiro', 'Dúvidas ou solicitações sobre pagamentos e faturas'),
('Comercial', 'Pedidos, planos ou informações sobre produtos e serviços'),
('Acesso', 'Problemas de login, senha ou autenticação'),
('Outros', 'Solicitações diversas não categorizadas');

-- ##AGENTS
INSERT INTO agents(name, email, department, level) VALUES
('Ana Souza', 'ana.souza@email.com', 'Suporte', 'Júnior'),
('Bruno Lima', 'bruno.lima@email.com', 'Suporte', 'Pleno'),
('Carla Ferreira', 'carla.ferreira@email.com', 'Financeiro', 'Pleno'),
('Diego Torres', 'diego.torres@email.com', 'Comercial', 'Sênior'),
('Fernanda Rocha', 'fernanda.rocha@email.com', 'Suporte', 'Coordenadora');


-- ##CUSTOMERS (100 registros aleatórios)
INSERT INTO customers(name, email, phone)
SELECT
  'Cliente' || i,
  'cliente' || i || '@exemplo.com',
  '(11) 9' || LPAD((10000000 + i)::text, 8, '0')
FROM generate_series(1,100) AS s(i);

-- ##TICKETS
INSERT INTO tickets (subject, description, priority, customer_id, agent_id, category_id, status_id)
VALUES
('Erro no login do sistema', 'Cliente relata não conseguir acessar a conta', 'ALTA', 1, 1, 4, 1),
('Fatura não recebida', 'Cliente não recebeu boleto do mês', 'MÉDIA', 2, 3, 2, 1),
('Plano incorreto', 'Cliente relata cobrança em plano diferente', 'MÉDIA', 3, 4, 3, 2),
('Sistema lento', 'Reclamação sobre lentidão no painel administrativo', 'ALTA', 4, 2, 1, 2),
('Alterar método de pagamento', 'Solicita mudança de cartão para boleto', 'BAIXA', 5, 3, 2, 3),
('Dúvida sobre upgrade', 'Cliente quer entender diferença entre planos', 'BAIXA', 6, 4, 3, 1),
('Senha expirada', 'Cliente não consegue redefinir senha', 'MÉDIA', 7, 1, 4, 1),
('Erro 500 na página principal', 'Falha ao tentar carregar dashboard', 'ALTA', 8, 2, 1, 2),
('Cancelar assinatura', 'Cliente deseja encerrar o contrato', 'MÉDIA', 9, 4, 3, 4),
('Atualização de dados cadastrais', 'Cliente solicita atualização de CPF', 'BAIXA', 10, 1, 5, 1),
('Erro ao atualizar cadastro', 'Cliente não consegue alterar informações pessoais', 'MÉDIA', 11, 1, 5, 1),
('Problema com boleto', 'Boleto gerado com valor incorreto', 'ALTA', 12, 3, 2, 2),
('Sistema fora do ar', 'Sistema indisponível no horário comercial', 'ALTA', 13, 2, 1, 2),
('Solicitação de nota fiscal', 'Cliente solicita nota fiscal de pagamento', 'BAIXA', 14, 3, 2, 4),
('Plano não ativado', 'Cliente fez upgrade mas não teve acesso liberado', 'ALTA', 15, 4, 3, 1),
('Erro de autenticação', 'Falha ao autenticar token de acesso', 'MÉDIA', 16, 1, 4, 2),
('Dúvida sobre cobrança', 'Cliente questiona taxa adicional', 'MÉDIA', 17, 3, 2, 3),
('Sugestão de melhoria', 'Cliente sugere novo recurso para o sistema', 'BAIXA', 18, 4, 5, 4),
('Ticket duplicado', 'Cliente abriu o mesmo chamado duas vezes', 'BAIXA', 19, 2, 1, 5),
('Alteração de e-mail', 'Solicita atualização de endereço de e-mail', 'BAIXA', 20, 1, 5, 1),
('Falha em relatório', 'Erro ao exportar dados para Excel', 'ALTA', 21, 2, 1, 2),
('Dúvida sobre desconto', 'Cliente pede explicação sobre valor da fatura', 'MÉDIA', 22, 3, 2, 4),
('Erro 404 no portal', 'Página de suporte não encontrada', 'ALTA', 23, 1, 1, 1),
('Acesso bloqueado', 'Conta bloqueada por tentativas de senha incorreta', 'MÉDIA', 24, 2, 4, 2),
('Solicitação de upgrade', 'Cliente deseja migrar para plano premium', 'BAIXA', 25, 4, 3, 3),
('Problema de sincronização', 'Dados não estão atualizando corretamente', 'ALTA', 26, 1, 1, 2),
('Reembolso não recebido', 'Cliente solicita atualização sobre reembolso', 'MÉDIA', 27, 3, 2, 4),
('Bug na dashboard', 'Indicadores não exibem valores corretos', 'ALTA', 28, 2, 1, 2),
('Senha redefinida com sucesso', 'Confirmação de redefinição de senha', 'BAIXA', 29, 1, 4, 4),
('Erro ao anexar arquivo', 'Cliente não consegue enviar anexos no ticket', 'MÉDIA', 30, 2, 1, 3),
('Troca de plano recusada', 'Sistema impede mudança de plano', 'MÉDIA', 31, 4, 3, 1),
('Problema na cobrança anual', 'Cobrança duplicada identificada', 'ALTA', 32, 3, 2, 2),
('Link inválido', 'Link de redefinição de senha expirado', 'MÉDIA', 33, 1, 4, 3),
('Integração com API falhando', 'Erro 500 em chamadas externas', 'ALTA', 34, 2, 1, 2),
('Fatura paga não reconhecida', 'Cliente relata pagamento não registrado', 'ALTA', 35, 3, 2, 3),
('Dúvida sobre contrato', 'Solicita cópia do contrato de serviço', 'BAIXA', 36, 4, 3, 4),
('Erro na importação de dados', 'Arquivo CSV não é aceito pelo sistema', 'MÉDIA', 37, 1, 1, 2),
('Solicitação de suporte urgente', 'Cliente VIP reporta instabilidade', 'ALTA', 38, 2, 5, 2),
('Sistema travando', 'Aplicativo fecha sozinho após login', 'ALTA', 39, 1, 1, 2),
('Configuração incorreta', 'Cliente não consegue configurar API key', 'MÉDIA', 40, 2, 1, 3),
('Cancelamento não concluído', 'Cliente tentou cancelar assinatura sem sucesso', 'MÉDIA', 41, 4, 3, 2),
('Bug visual', 'Interface desconfigurada após atualização', 'BAIXA', 42, 2, 1, 3),
('Alteração de titularidade', 'Cliente deseja transferir conta', 'BAIXA', 43, 1, 5, 4),
('Erro de login social', 'Login via Google falhando', 'MÉDIA', 44, 1, 4, 2),
('Ticket não resolvido', 'Cliente reabriu ticket anterior', 'MÉDIA', 45, 2, 1, 3),
('Pedido de relatório customizado', 'Cliente solicita relatório específico', 'BAIXA', 46, 4, 5, 4),
('Fatura com juros indevidos', 'Cobrança com juros aplicados incorretamente', 'ALTA', 47, 3, 2, 3),
('Erro em campo obrigatório', 'Formulário impede envio mesmo com campos preenchidos', 'MÉDIA', 48, 2, 1, 1),
('Problema de compatibilidade', 'Sistema não funciona em navegador Safari', 'MÉDIA', 49, 1, 1, 2),
('Solicitação de treinamento', 'Cliente pede vídeo explicativo sobre novo recurso', 'BAIXA', 50, 4, 5, 4),
('Erro ao salvar ticket', 'Sistema retorna timeout ao salvar chamado', 'ALTA', 51, 2, 1, 2),
('Problema de segurança', 'Cliente suspeita de acesso indevido', 'ALTA', 52, 1, 4, 1),
('Solicitação de backup', 'Cliente quer cópia de segurança dos dados', 'BAIXA', 53, 1, 5, 3),
('Falha em integração', 'Erro ao conectar com serviço externo', 'ALTA', 54, 2, 1, 2),
('Dúvida sobre política de privacidade', 'Cliente pede mais informações sobre LGPD', 'BAIXA', 55, 4, 5, 4),
('Atualização de versão', 'Cliente reporta erro após atualização', 'MÉDIA', 56, 2, 1, 2),
('Boleto atrasado', 'Cliente solicita novo boleto após vencimento', 'MÉDIA', 57, 3, 2, 3),
('Erro ao exportar relatório PDF', 'Botão de exportação não responde', 'MÉDIA', 58, 1, 1, 2),
('Cliente não reconhece cobrança', 'Cobrança indevida no cartão', 'ALTA', 59, 3, 2, 3),
('Configuração de DNS incorreta', 'Domínio não está apontando corretamente', 'ALTA', 60, 2, 1, 2),
('Conta suspensa', 'Cliente relata bloqueio indevido', 'MÉDIA', 61, 1, 4, 2),
('Erro de timezone', 'Horário exibido incorretamente nos relatórios', 'BAIXA', 62, 2, 1, 3),
('Dúvida sobre API', 'Cliente pede documentação da API', 'BAIXA', 63, 4, 5, 4),
('Bug no painel financeiro', 'Totais não somam corretamente', 'MÉDIA', 64, 3, 2, 2),
('Alterar forma de contato', 'Cliente quer mudar canal de comunicação', 'BAIXA', 65, 4, 5, 4),
('Erro de permissão', 'Usuário não autorizado para acessar recurso', 'ALTA', 66, 1, 1, 2),
('Requisição pendente', 'Ticket criado sem resposta há mais de 3 dias', 'MÉDIA', 67, 2, 1, 3),
('Falha no carregamento', 'Página inicial não carrega completamente', 'MÉDIA', 68, 1, 1, 2),
('Cliente insatisfeito com suporte', 'Feedback negativo recebido', 'ALTA', 69, 4, 5, 3),
('Erro ao gerar contrato', 'Documento PDF sai em branco', 'MÉDIA', 70, 2, 1, 1),
('Problema com login', 'Cliente esqueceu senha e link não funciona', 'MÉDIA', 71, 1, 4, 2),
('Falha em pagamento', 'Erro ao processar cartão de crédito', 'ALTA', 72, 3, 2, 2),
('Dúvida sobre uso da plataforma', 'Cliente quer saber como usar recurso X', 'BAIXA', 73, 4, 5, 4),
('Erro no envio de e-mails', 'Notificações automáticas não estão sendo disparadas', 'ALTA', 74, 2, 1, 2),
('Atualização pendente', 'Sistema informa versão antiga mesmo após update', 'MÉDIA', 75, 1, 1, 3),
('Problema na exportação CSV', 'Arquivo gerado com colunas trocadas', 'MÉDIA', 76, 2, 1, 3),
('Solicitação de cancelamento de cobrança', 'Cliente quer cancelar débito futuro', 'MÉDIA', 77, 3, 2, 4),
('Erro de configuração SMTP', 'Servidor de e-mail não autenticando', 'ALTA', 78, 1, 1, 2),
('Lentidão geral', 'Sistema muito lento no horário de pico', 'ALTA', 79, 2, 1, 2),
('Ticket encerrado automaticamente', 'Ticket fechado sem resposta', 'BAIXA', 80, 4, 5, 5),
('Erro de fuso horário', 'Eventos exibidos com hora incorreta', 'BAIXA', 81, 2, 1, 3),
('Cliente quer atualizar plano', 'Solicitação de migração para plano empresarial', 'BAIXA', 82, 4, 3, 4),
('Erro no gráfico de vendas', 'Gráfico não carrega dados', 'MÉDIA', 83, 2, 1, 2),
('Problema em integração ERP', 'Falha ao enviar dados para sistema externo', 'ALTA', 84, 2, 1, 2),
('Dúvida sobre taxas adicionais', 'Cliente questiona taxa de adesão', 'MÉDIA', 85, 3, 2, 3),
('Acesso intermitente', 'Conexão cai após alguns minutos', 'MÉDIA', 86, 1, 1, 2),
('Erro no painel de controle', 'Configurações não salvam corretamente', 'MÉDIA', 87, 2, 1, 2),
('Pedido de renovação de contrato', 'Cliente quer renovar plano anual', 'BAIXA', 88, 4, 3, 4),
('Problema com API key', 'Cliente não consegue gerar nova chave', 'ALTA', 89, 1, 4, 1),
('Ticket arquivado', 'Ticket encerrado e arquivado no sistema', 'BAIXA', 90, 4, 5, 5),
('Erro no login mobile', 'Aplicativo não reconhece credenciais', 'MÉDIA', 91, 1, 4, 2),
('Falha ao atualizar senha', 'Erro ao redefinir senha via app', 'MÉDIA', 92, 1, 4, 3),
('Erro em relatório financeiro', 'Valores não batem com o dashboard', 'ALTA', 93, 3, 2, 2),
('Cliente não consegue emitir boleto', 'Erro no botão de emissão', 'MÉDIA', 94, 3, 2, 1),
('Bug na listagem de usuários', 'Usuários duplicados na tela principal', 'ALTA', 95, 2, 1, 2),
('Dúvida sobre plano básico', 'Cliente quer entender limites do plano', 'BAIXA', 96, 4, 3, 4),
('Problema de login intermitente', 'Cliente consegue logar apenas às vezes', 'MÉDIA', 97, 1, 4, 2),
('Solicitação de relatório mensal', 'Cliente pede relatório automático mensal', 'BAIXA', 98, 4, 5, 4),
('Erro ao enviar formulário', 'Sistema retorna erro de validação', 'MÉDIA', 99, 2, 1, 2),
('Ticket encerrado manualmente', 'Agente encerrou ticket após resolução', 'BAIXA', 100, 4, 5, 5);
